### ISSUE TITLE
Purge Entity Cache not clearing filtered routes

### ISSUE THREAD

**Issue by abhijit-hl** [TupiC/strapi-cache#38]
### Bug: Purge Entity Cache Doesn't Clear Filtered Route Cache
Plugin Name: strapi-cache
Strapi Version: 5.x
Plugin Version: Latest (as of July 2025)
Cache Strategy: Redis
Entity Type: Collection Type (cities)

When I click "Purge Entity Cache" for the cities collection type from the Strapi Admin panel, the cache for /api/cities/:id is successfully cleared. 
However, any filtered or populated GET routes are not cleared, even though they reference the same entity, for example:
/api/cities?filters[city_name][$eq]=cityName&populate=city_section_info

These routes still return cached responses after entity purge, showing HIT in the logs.

###  Expected Behavior
When I click “Purge Entity Cache” for cities, it should also:

Invalidate any cache keys related to filtered or populated versions of cities

Optionally, support tag-based invalidation (ctx.state.cacheTags) if implemented

**Comment by addoinc** [comment]
Please check below:

<img width="1421" height="393" alt="Image" src="https://github.com/user-attachments/assets/5452dbd5-0b91-4aa8-b1b6-e4c7aa75f5af" />

<img width="826" height="250" alt="Image" src="https://github.com/user-attachments/assets/1872183b-ec5a-4b39-9145-d95993815127" />

<img width="1425" height="386" alt="Image" src="https://github.com/user-attachments/assets/20908a9f-df9f-4449-9c7b-63e7e00638ff" />

**Comment by addoinc** [comment]
I have seen a warning in my staging env, and it could be relevant in solving this issue. It seems plugin is unable to load the cachebale routes. Please check below:

<img width="1205" height="531" alt="Image" src="https://github.com/user-attachments/assets/6e185888-214c-4f2e-b155-5a1980963370" />

<img width="742" height="431" alt="Image" src="https://github.com/user-attachments/assets/9db148ff-5489-478f-85e6-dbf010f411d0" />

**Comment by TupiC** [comment]
Fixed in [v1.5.6](https://github.com/TupiC/strapi-cache/releases/tag/v1.5.6)

**Comment by addoinc** [comment]
I have tested this in v1.5.6 and I can still see the same bug.  It still gives warning `unable to fetch cachable routes` and 'purging entity cache' does not result in the entity being purged.

Though the warning only appears if I close the tab and again open the strapi instance, it disappears after appearing once.

**Comment by TupiC** [comment]
> I have tested this in v1.5.6 and I can still see the same bug.  It still gives warning `unable to fetch cachable routes` and 'purging entity cache' does not result in the entity being purged.
> 
> Though the warning only appears if I close the tab and again open the strapi instance, it disappears after appearing once.

I just fixed the actual issue "Bug: Purge Entity Cache Doesn't Clear Filtered Route Cache". This was also the reason I closed this issue. But lets fix your problem now. Did you set the correct permissions for your user you are testing this with? Also can you please create a minimalistic reproduction production. This would make it easier to debug your issue.👍🏽

**Comment by abhijit-hl** [comment]
@TupiC What is fixed here "Bug: Purge Entity Cache Doesn't Clear Filtered Route Cache" ? I mean how can I clear the cache for any filtered get request which does not use any document id in GET API ?

**Comment by TupiC** [comment]
You can not at the moment. You would need to programmatically clear it.

**Comment by addoinc** [comment]
> I just fixed the actual issue "Bug: Purge Entity Cache Doesn't Clear Filtered Route Cache". This was also the reason I closed this issue. But lets fix your problem now. Did you set the correct permissions for your user you are testing this with? Also can you please create a minimalistic reproduction production. This would make it easier to debug your issue.👍🏽

I am testing as a super admin, I will check if I can share our dev instance which is online, to you but I am not sure if it is possible.

**Comment by abhijit-hl** [comment]
> You can not at the moment. You would need to programmatically clear it.

@TupiC How to can I clear filtered routes programmatically where I don't have the entry id present in API request ? 
Can i add my custom request somewhere and when purge entity cache button in clicked then it will look that custom API and clear the cache accordingly ?

**Comment by TupiC** [comment]
> [@TupiC](https://github.com/TupiC) How to can I clear filtered routes programmatically where I don't have the entry id present in API request ? Can i add my custom request somewhere and when purge entity cache button in clicked then it will look that custom API and clear the cache accordingly ?

Hi @abhijit-hl, sorry for the late reply. You can clear specific routes programmatically even without the entry ID; you'll just need some custom logic to identify the correct cache entry (example here: https://github.com/TupiC/strapi-cache/issues/10#issuecomment-2846656953). Let me know if you need anything else.


> [@TupiC](https://github.com/TupiC) Hi, Is there any update regarding this issue?
> 
> I'm currently using version 1.5.7, and I'm clearing the cache using the native "Purge Entity Cache " button in the Strapi Admin UI (the built-in cache purge option). However, even after running it, the cache key is still present in Redis.
> 
> For example, after clicking the purge button, I can open my Redis container and still see the key stored — it doesn’t get removed as expected.

Thank you for the remark, @DanielYaako1. Could you explain in detail what you expect and what the current behavior is, preferably with some real cache keys? A minimal reproducible repository would also be extremely helpful (maybe use the [playground](https://github.com/TupiC/strapi-cache/tree/main/playground) folder)

**Comment by TupiC** [comment]
> Plugin works fine if route "**find**" is used (ex. GET /api/endpoint-1). But if I create a new route "**filterByBrand**" (ex. GET /api/endpoint-2) then while purging the cache only the data from the first example is clearing. I cannot clear the cache for "api/endpoint-2".

Hi @web-admin,

Could you please provide the actual cache keys stored for both routes ("find" and "filterByBrand")? It would also help to know which of these keys should be cleared during the cache purge and which ones are expected to remain untouched.

Thanks!

**Comment by web-admin** [comment]
> > Plugin works fine if route "**find**" is used (ex. GET /api/endpoint-1). But if I create a new route "**filterByBrand**" (ex. GET /api/endpoint-2) then while purging the cache only the data from the first example is clearing. I cannot clear the cache for "api/endpoint-2".
> 
> Hi [@web-admin](https://github.com/web-admin),
> 
> Could you please provide the actual cache keys stored for both routes ("find" and "filterByBrand")? It would also help to know which of these keys should be cleared during the cache purge and which ones are expected to remain untouched.
> 
> Thanks!

Hi @TupiC ,

Thanks for replying.

Please find attached screens of both endpoints.

Plugin works perfectly fine for "**find**" route (cache key: GET:api/cs-sb-telegrams) but clearing the cache for "**filterByBrand**" (cache key: GET:/api/telegram-messages) not working. Both keys saving fine in Redis but when I press the purge button in CMS only the first one disappear.

I also trying to create extension of this plugin and clean in "programmatically" as you suggested above but no results so far. When pressing "purge" button in CMS for "cs-sb-telegrams" I want to clean "telegram-messages" keys too.

<img width="1213" height="439" alt="Image" src="https://github.com/user-attachments/assets/ced15506-3021-4d85-81a8-5db1942bb817" />
<img width="1224" height="444" alt="Image" src="https://github.com/user-attachments/assets/a2a7ff65-9404-4173-a0e2-f6388c43d178" />

)

**Comment by TupiC** [comment]
> ... Is it a chance for any workaround?

Hm, you could solve it programmatically or at the plugin's settings page 🤔

**Comment by TupiC** [comment]
> Yes, 1.6.1-rc.2 works fine, thanks! However I cannot see "Purge Cache" button in Settings section... Just the field where I can type the key.
> 
> <img width="1631" height="1013" alt="Image" src="https://github.com/user-attachments/assets/b3b088a6-cf57-4147-8d4b-17c77e225e3f" />

As soon as you enter a key the button will appear. Will change this in the next release.

**Comment by web-admin** [comment]
Unfortunately, I cannot see it - it doesn't matter I paste there something or enter.

**Comment by TupiC** [comment]
> Unfortunately, I cannot see it - it doesn't matter I paste there something or enter.

Do you have the correct permission set?
